# Generated by Django 4.2.2 on 2023-06-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='df-sdfs', max_length=255),
            preserve_default=False,
        ),
    ]
